### ISSUE TITLE
compilation failed on Timed annotation

### ISSUE THREAD

**Issue by MDS-2018** [hipster-labs/generator-jhipster-entity-audit#103]
hi this is my first time using this module
I have generated a jhipster app then I installed the module using npm, and used it using yoman but when I use the maven wrapper to deploy my app locally the compilation step is a failure due to the following exception:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project mbc-cb: Compilation failure: Compilation failure:
[ERROR] /C:/Users/win 10/Documents/salle de sport/src/main/java/com/mbc_cb/web/rest/EntityAuditResource.java:[22,39] package com.codahale.metrics.annotation does not exist
[ERROR] /C:/Users/win 10/Documents/salle de sport/src/main/java/com/mbc_cb/web/rest/EntityAuditResource.java:[51,6] cannot find symbol
[ERROR]   symbol:   class Timed
[ERROR]   location: class com.mbc_cb.web.rest.EntityAuditResource
[ERROR] /C:/Users/win 10/Documents/salle de sport/src/main/java/com/mbc_cb/web/rest/EntityAuditResource.java:[72,6] cannot find symbol
[ERROR]   symbol:   class Timed
[ERROR]   location: class com.mbc_cb.web.rest.EntityAuditResource
[ERROR] -> [Help 1]
```

what to do ?

I m using latest jhipster version 5.8

**Comment by ruddell** [comment]
This annotation was removed in JHipster v5.8 due to the Micrometer migration.  You can remove the annotation and it should compile.

**Comment by murdos** [comment]
https://github.com/hipster-labs/generator-jhipster-entity-audit/issues/110 already covers this issue, I suggest to close it as a duplicate
