### ISSUE TITLE
Not working with version 5

### ISSUE THREAD

**Issue by fakher-saafi** [hipster-labs/generator-jhipster-entity-audit#104]
![screenshot from 2019-02-13 14-42-51](https://user-images.githubusercontent.com/18703226/52715844-c26ff980-2f9d-11e9-8815-35b925c3e2b6.png)
When I run the command "yo jhipster-entity-audit" it gives me this error.
My current jhipster version is 5.8.1

**Comment by murdos** [comment]
Issue fixed with #119 ; a new version should be released soon
