### ISSUE TITLE
Error with JHipster v5.8.2

### ISSUE THREAD

**Issue by ernsyn** [hipster-labs/generator-jhipster-entity-audit#110]
I'm getting the following error when running this generator with jhipster v5.8.2. 

Running the command below and adding a "default" throws the same error message.

➜  jhipster-db git:(master) yo jhipster-entity-audit
events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: this.getJhipsterAppConfig is not a function
    at module.exports.readConfig (/usr/local/lib/node_modules/generator-jhipster-entity-audit/generators/app/index.js:23:33)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-jhipster-entity-audit/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:424:27)
    at /usr/local/lib/node_modules/generator-jhipster-entity-audit/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/generator-jhipster-entity-audit/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/usr/local/lib/node_modules/generator-jhipster-entity-audit/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:425:13)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

Anyone knows what I did wrong or is this a compatibility issue? 

Looking forward to your replies.

**Comment by alexb-1983** [comment]
I forced to install the 'master' version:
npm install -g git+https://github.com/hipster-labs/generator-jhipster-entity-audit.git

after that it worked.

**Comment by ernsyn** [comment]
I just tried your suggestion and it works. After that I got other issues such as missing import for the @Timed annotation and also some syntax error in the cache creation. 

Btw, any idea why installing from master works?

**Comment by alexb-1983** [comment]
I also removed @Timed as said here #103.
I think that actual master has not yet released.

**Comment by ernsyn** [comment]
Yup, I did as per that ticket. I had a couple others as well. 

For eg. in CacheConfiguration, it added "createCache(cm, com.jhipster.domain.EntityAuditEvent.class.getName());" which is no longer valid as the new version uses the lambda syntax. Changed it to "cm.createCache(com.jhipster.domain.EntityAuditEvent.class.getName(), jcacheConfiguration);" solves the problem.

Now i'm fixing a route that don't exists.

**Comment by deepu105** [comment]
I'm not having a lot of time to maintain this project so PRs will be appreciated guys

**Comment by murdos** [comment]
The original error (missing `getJhipsterAppConfig` function) was fixed with https://github.com/hipster-labs/generator-jhipster-entity-audit/pull/105.

The @Timed issue will be fixed by https://github.com/hipster-labs/generator-jhipster-entity-audit/pull/111

**Comment by murdos** [comment]
Issue fixed with #119 ; a new version should be released soon
