### ISSUE TITLE
Change default deletion behavior to support soft deletion

### ISSUE THREAD

**Issue by smunir** [hipster-labs/generator-jhipster-entity-audit#114]
Does this sub-generator handle default delete behavior. I would like soft delete using this sub-generator. This is mentioned in marketplace label but I couldn't find anything in docs or examples.

**Comment by murdos** [comment]
No, this feature is not implemented, and I'm not certain it belongs to this module.

**Comment by deepu105** [comment]
Yes there is no such feature. If you implement soft delete, it is just an update operation and will be captured in update audits
