### ISSUE TITLE
It's might be worth to make AbstractAuditingEntity properties READ_ONLY for JSON

### ISSUE THREAD

**Issue by ArseniyShestakov** [hipster-labs/generator-jhipster-entity-audit#117]
I'll just leave it as issue and not PR because I might miss something important so whoever going to fix this module for latest version can look into this. Though there practically no reason to keep audit properties writable by JSON deserialization since no one ever want to get them from clients.

So all ```createdBy```, ```createdDate```, ```lastModifiedBy```, ```lastModifiedDate``` can use:
```
@JsonProperty(access = Access.READ_ONLY)
```

**Comment by DanielFran** [comment]
Closing, since we migrate to a new blueprint version.
If you found any issue with latest version, please open a new issue.
