### ISSUE TITLE
entityAuditInterceptor required?

### ISSUE THREAD

**Issue by gbrehmer** [hipster-labs/generator-jhipster-entity-audit#12]
Sorry, I probably do not understand the benefits of entityAuditInterceptor. Is this interceptor really required? Because auditing fields are set on backend side (by AuditingEntityListener).

**Comment by deepu105** [comment]
Somehow the bean validation kicks in before the fields are set at backend
so this is a workaround to fix that, there should be a better way but I
couldnt figure out. if you can fix it plz PR

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
fixed via https://github.com/hipster-labs/generator-jhipster-entity-audit/releases/tag/v2.0.1
