### ISSUE TITLE
entityAudit state does not activate

### ISSUE THREAD

**Issue by sanderpost** [hipster-labs/generator-jhipster-entity-audit#13]
Hi m8,

For some reason the translatePartialLoader in the state entityAudit prevents the entityAudit state from activating without logging an exception whatsoever.

After commenting out the lines the state did load. 
```
            resolve: {
//            	translatePartialLoader: ['$translate', '$translatePartialLoader', function ($translate, $translatePartialLoader) {
//					$translatePartialLoader.addPart('audits');
//					return $translate.refresh();
//            	}]
            }
```
This behaviour might be caused due to my project not being multi-lingual?

**Comment by deepu105** [comment]
its fixed in master and will be available in the next release, you can comment this out for the mean time
