### ISSUE TITLE
why “SpringSecurityAuditorAware” class is disabled

### ISSUE THREAD

**Issue by kisixing** [hipster-labs/generator-jhipster-entity-audit#145]
dear ：
   I use this generator to create jhipster application's audit module. And I use the 'common jhipster aduit' type. Something wrong happened, the 'getCurrentAuditor' method is disabled 
in 'SpringSecurityAuditorAware'.

/**
 * Implementation of AuditorAware based on Spring Security.
 */
@Component
public class SpringSecurityAuditorAware implements AuditorAware<String> {

    @Override
    public Optional<String> getCurrentAuditor() {
    	System.out.println(SecurityUtils.getCurrentUserJWT());
        return Optional.of(SecurityUtils.getCurrentUserJWT().orElse(Constants.SYSTEM_ACCOUNT));
    }
}

@Configuration
@EnableJpaRepositories("com.lianmed.genl1.repository")
@EnableJpaAuditing(auditorAwareRef = "springSecurityAuditorAware")
@EnableTransactionManagement
public class DatabaseConfiguration {

    private final Logger log = LoggerFactory.getLogger(DatabaseConfiguration.class);
    
}
But I found if @EntityListeners use the base 'AuditingEntityListener' instead of 'EntityAuditEventListener', 'SpringSecurityAuditorAware' is right , at the same time 
the function of 'EntityAuditEventListener' is in vain

**Comment by DanielFran** [comment]
Closing, since we migrate to a new blueprint version.
If you found any issue with latest version, please open a new issue.
