### ISSUE TITLE
Not compatible with angular 9+

### ISSUE THREAD

**Issue by edy-ap** [hipster-labs/generator-jhipster-entity-audit#148]
This likely means that the library (ng-diff-match-patch) which declares DiffMatchPatchModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

**Comment by bukohub** [comment]
I have the same error. Iuk.

**Comment by bukohub** [comment]
Men, I found the solution this problema. You need update **ng-diff-match-patch** to last version.

**Comment by deepu105** [comment]
Would you be willing to a PR?

**Comment by murdos** [comment]
There's already a PR for that (https://github.com/hipster-labs/generator-jhipster-entity-audit/pull/147), but I'm not in favor of merging it until we know where this new version of ng-diff-match-patch comes from (https://github.com/elliotforbes/ng-diff-match-patch/issues/39)

**Comment by deepu105** [comment]
Oh I didn't realize that we are changing lib. Ok I'll leave it to you then

**Comment by bukohub** [comment]
@murdos, @deepu105. Actually, there are some problems with generator-jhipster-entity-audit in angular 9. 
1. ng-diff-match-patch, (I solved that solution with update version, but @murdos  has reason).
2. admin-routing.module.ts, generates two commas in his route.
3. entity-audit-modal.component.html, generates a  <pre class="code" id="resultChanges" diff [left]="left" [right]="right"></pre>, that generates issue, in tags left and right (angular version problem). 

In all the time using entity-audit, this was my problems.

**Comment by bukohub** [comment]
This generate is incredible (really). I would like contribute it, but I don't know how to do a PR.

**Comment by vaibhavg12** [comment]
@bukohub how did you resolve no 3? 

> 
> 
> @murdos, @deepu105. Actually, there are some problems with generator-jhipster-entity-audit in angular 9.
> 
>     1. ng-diff-match-patch, (I solved that solution with update version, but @murdos  has reason).
> 
>     2. admin-routing.module.ts, generates two commas in his route.
> 
>     3. entity-audit-modal.component.html, generates a  <pre class="code" id="resultChanges" diff [left]="left" [right]="right">, that generates issue, in tags left and right (angular version problem).
> 
> 
> In all the time using entity-audit, this was my problems.

**Comment by dhavalmshah** [comment]
> @bukohub how did you resolve no 3?
> 
> > @murdos, @deepu105. Actually, there are some problems with generator-jhipster-entity-audit in angular 9.
> > ```
> > 1. ng-diff-match-patch, (I solved that solution with update version, but @murdos  has reason).
> > 
> > 2. admin-routing.module.ts, generates two commas in his route.
> > 
> > 3. entity-audit-modal.component.html, generates a  <pre class="code" id="resultChanges" diff [left]="left" [right]="right">, that generates issue, in tags left and right (angular version problem).
> > ```
> > 
> > 
> > In all the time using entity-audit, this was my problems.

Probably there are much better ways, I changed the entity-audit-modal.component.ts to make left and right as regular strings:

`
export class EntityAuditModalComponent {
  action?: string;
  left: string = "";
  right: string = "";
`
