### ISSUE TITLE
is there any way let it support Vue front-end?

### ISSUE THREAD

**Issue by china-fengguan** [hipster-labs/generator-jhipster-entity-audit#149]
As a Mongo and Vue user, spring boot part looks good and jv_head_id, jv_snapshots had been created and record entity history. Only Vue part has nothing changed, there is no new item like 'Entity audit log' in nevbar, either no router info chaged in router index file.

**Comment by DanielFran** [comment]
Closing, since we migrate to a new blueprint version.
If you found any issue with latest version, please open a new issue.
