### ISSUE TITLE
Problem with timezone

### ISSUE THREAD

**Issue by micobarac** [hipster-labs/generator-jhipster-entity-audit#150]
My current timezone is `UTC+2`.

`created_date` is written using MySQL `now()`, which ignores timezone:

`2020-05-26 10:33:59`

`last_modified_date` is written with timezone in mind:

`2020-05-26 08:34:27`

As you can see, there is a 2 hour difference.

How do I make this right? Any help would be appreciated.

**Comment by kaidohallik** [comment]
The latest `generator-jhipster` assumes that MySql database timezone is UTC.

2 possible solutions:
* Solution 1. Set your MySql database timezone to UTC.
* Solution 2. Remove UTC from JDBC and Hibernate configuration in the generated project:
    - JDBC: remove `&serverTimezone=UTC` from https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/resources/config/application-dev.yml.ejs#L217 and from https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/resources/config/application-prod.yml.ejs#L183
    - Hibernate: remove `hibernate.jdbc.time_zone: UTC` from https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/resources/config/application.yml.ejs#L216

**Comment by micobarac** [comment]
Ok, thanks :)
