### ISSUE TITLE
[JaVers] wrong audited entities types returned by REST endpoint

### ISSUE THREAD

**Issue by nickshoe** [hipster-labs/generator-jhipster-entity-audit#154]
I've enabled entity aduting on my existing JHipster project.

My entities names all ends with the `Entity` suffix (e.g. `TimelogEntity`), but the `JaversEntityAuditResource` seems to not take care of it.

Generated code:
```java
    /**
     * fetches all the audited entity types
     *
     * @return
     */
    @RequestMapping(value = "/audits/entity/all",
        method = RequestMethod.GET,
        produces = MediaType.APPLICATION_JSON_VALUE)
    @PreAuthorize("hasRole(\"" + AuthoritiesConstants.ADMIN + "\")")
    public List<String> getAuditedEntities() {

      return Arrays.asList("Timelog");
    }
```

This results in the following exception being thrown when trying to load the change list of an entity from the UI:
`java.lang.ClassNotFoundException: it.blutec.bludesk.domain.Timelog`

Suggested fix: consider the presence of the suffix in the code generation process.
```java
    /**
     * fetches all the audited entity types
     *
     * @return
     */
    @RequestMapping(value = "/audits/entity/all",
        method = RequestMethod.GET,
        produces = MediaType.APPLICATION_JSON_VALUE)
    @PreAuthorize("hasRole(\"" + AuthoritiesConstants.ADMIN + "\")")
    public List<String> getAuditedEntities() {

      return Arrays.asList("TimelogEntity");
    }
```

**Comment by DanielFran** [comment]
Closing, since we migrate to a new blueprint version.
If you found any issue with latest version, please open a new issue.
