### ISSUE TITLE
EntityAuditEvent: Hibernate Wrong Column Type Exception in Unit Tests

### ISSUE THREAD

**Issue by flexxis** [hipster-labs/generator-jhipster-entity-audit#16]
Hi,

when i generate a new jhipster project and create some entities, all my unit tests work just fine. [2] [3]
However, after generating the audit feature for all entities [4], all unit tests fail with the following exception under [1]. 
I created the Project with MySQL as Develop DB and here it works. For Unit Tests H2 is used, so my assumption was that there must be a problem between liquibase, H2 dialect and / or hibernate ?
Liquibase Changelog xml [5] shows me 
 `<column name="entity_value" type="clob"/>`
, so i cannot figure out where the expected varchar(255) does come from.

Can you confirm this problem?

PS: JHipster and Subgenerators are up to date.

Thanks in advance
Felix

[1]
`Caused by: org.hibernate.HibernateException: Wrong column type in TESTPROJ.PUBLIC.JHI_ENTITY_AUDIT_EVENT for column entity_value. Found: clob, expected: varchar(255)
	at org.hibernate.mapping.Table.validateColumns(Table.java:373) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.cfg.Configuration.validateSchema(Configuration.java:1338) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.tool.hbm2ddl.SchemaValidator.validate(SchemaValidator.java:175) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:525) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1859) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:857) ~[hibernate-entitymanager-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:850) ~[hibernate-entitymanager-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.withTccl(ClassLoaderServiceImpl.java:425) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:849) ~[hibernate-entitymanager-4.3.11.Final.jar:4.3.11.Final]
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60) ~[spring-orm-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:343) ~[spring-orm-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:318) ~[spring-orm-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	... 41 common frames omitted`

[2] yo jhipster

? (1/15) What is the base name of your application? testProj
? (2/15) What is your default Java package name? de.test
? (3/15) Which *type* of authentication would you like to use? HTTP Session Auth
entication (stateful, default Spring Security mechanism)
? (4/15) Which *type* of database would you like to use? SQL (H2, MySQL, Postgre
SQL, Oracle)
? (5/15) Which *production* database would you like to use? MySQL
? (6/15) Which *development* database would you like to use? H2 with in-memory p
ersistence
? (7/15) Do you want to use Hibernate 2nd level cache? No
? (8/15) Do you want to use a search engine in your application? No
? (9/15) Do you want to use clustered HTTP sessions? No
? (10/15) Do you want to use WebSockets? No
? (11/15) Would you like to use Maven or Gradle for building the backend? Maven
? (12/15) Would you like to use Grunt or Gulp.js for building the frontend? Grun
t (recommended)
? (13/15) Would you like to use the LibSass stylesheet preprocessor for your CSS
? No
? (14/15) Would you like to enable translation support with Angular Translate? N
o
? (15/15) Which testing frameworks would you like to use? Gatling

[3] yo jhipster:entity Foo

The entity Foo is being created.
Generating field #1
? Do you want to add a field to your entity? Yes
? What is the name of your field? bar
? What is the type of your field? String
? Do you want to add validation rules to your field? Yes
? Which validation rules do you want to add? Required

[4]yo jhipster-entity-audit

(!) require('yeoman-generator').generators.Base is deprecated. Use require('yeoman-generator').Base directly
Composing JHipster configuration with module entity-audit
Welcome to the JHipster Entity Audit Generator! v1.0.7

Reading the JHipster project configuration for your module
? Do you want to enable audit for all existing entities? Yes, update all
? Do you want to add an audit log page for entities? Yes

[5] liquibase changelog

`    
    <changeSet id="20160222094031" author="jhipster">
        <createTable tableName="jhi_entity_audit_event">
            <column name="id" type="bigint" autoIncrement="${autoIncrement}">
                <constraints primaryKey="true" nullable="false"/>
            </column>
            <column name="entity_id" type="bigint">
                <constraints nullable="false" />
            </column>
            <column name="entity_type" type="varchar(255)">
                <constraints nullable="false" />
            </column>
            <column name="action" type="varchar(20)">
                <constraints nullable="false" />
            </column>
            <column name="entity_value" type="clob"/>
            <column name="commit_version" type="integer"/>
            <column name="modified_by" type="varchar(100)"/>
            <column name="modified_date" type="timestamp">
                <constraints nullable="false" />
            </column>
        </createTable>
        <dropDefaultValue tableName="jhi_entity_audit_event" columnName="modified_date" columnDataType="datetime"/>
        
    </changeSet>
</databaseChangeLog>`

**Comment by andrewLS10** [comment]
Workaround is to edit the file:
./src/main/java/nz/co/logisticsoftware/ls10deliver/web/domain/EntityAuditEvent.java

Add the @Lob line below:
    @Column(name = "entity_value")
    @Lob
    private String entityValue;

Atleast it worked for me.

**Comment by deepu105** [comment]
thats strange coz this works without issue when I use h2 as dev DB @atomfrede do you have any idea on this?

@andidev any insights on the lob thing?

**Comment by andrewLS10** [comment]
True. The problem shows up with MySQL.

**Comment by andidev** [comment]
The entity audit module seems to generate the entityValue field as a clob instead of a varchar(255). 

Could you please provide the entity json files causing this issue. It's located in the .jhipster folder

**Comment by deepu105** [comment]
The value field is set as clob intentionally as it will hold the entity snapshot as JSON, I guess the issue here is clob not being supported in mySQL, will setting s DB specific value for this help? what should work for all our SQL DB? clob works for oracle and h2

**Comment by andidev** [comment]
We have a similar liquibase MySQL issue in #2934 though I don't think they are related

**Comment by objectArtz** [comment]
The Workaroung with @Lob also worked for me, thanks!

I have just created two new virgin projects : a) with H2 b) with MySQL as Develop Env. Both cause the same clob errors in the unit tests, so i only consider the second one.

I wanted to use a minimal test configuration to make it simple - e.g. i left Elastic Search Functionality - but that actually made the Entity Audit Page show nothing after clicking on it in the navbar. If the Entity Audit Plugin depends on Elastic Search, in future it would be a good idea to enforce this in the generator dialog or at leat give a hint ;-)

My Foo Entity has following json:
`{
    "relationships": [],
    "fields": [
        {
            "fieldId": 1,
            "fieldName": "bar",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20160226150144",
    "dto": "no",
    "service": "no",
    "pagination": "no"
}`

Database settings in .yo-rc.json
`{
  "generator-jhipster": {
    "baseName": "neuProjMysql",
    "packageName": "de.test",
    "packageFolder": "de/test",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "useSass": false,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "rememberMeKey": "f52bbe09c570a7fe8f2b8bb0cfeeaec58fbd85f7",
    "testFrameworks": [
      "gatling"
    ]
  }
}`


SQL Create for jhi_entity_audit_event Table

> CREATE TABLE `jhi_entity_audit_event` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `entity_id` bigint(20) NOT NULL,
  `entity_type` varchar(255) NOT NULL,
  `action` varchar(20) NOT NULL,
  `entity_value` longtext,
  `commit_version` int(11) DEFAULT NULL,
  `modified_by` varchar(100) DEFAULT NULL,
  `modified_date` timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;


So, Mysql converted the liquibase clob into a longtext type. The app actually works in DEV and it seems that LONGTEXT is the mysql type for clob ?  http://dev.mysql.com/doc/refman/5.7/en/blob.html

**Comment by deepu105** [comment]
It doesnt rely on elasticsearch. Ill check these out when I find time

Thanks & Regards,
Deepu

**Comment by objectArtz** [comment]
One little remark in order to get all tests passed:  in addition to @Lob, in all create<Entity> tests one line has to be added manually:

`foo.setCreatedBy("testUser");`

otherwise the request is invalidated and you get an 400 status code insted auf 201.

For update and delete,  database is is initalized and system user set.

**Comment by tomvanrossom** [comment]
Thanks @objectArtz, you are right: by initializing the "createdBy" all my tests run

**Comment by deepu105** [comment]
can someone PR this?

**Comment by flexxis** [comment]
Hi,
sorry for answering late. Not sure, what a PR could look like, but i think you alread put the log flag on the entityValue field for EntityAuditEvent (v. 2.03). As  the createdBy user ist annotated as notNull anymore, all tests should be fine.  i think this ticket can be closed.
