### ISSUE TITLE
TypeError: Cannot read property 'changelogDate' of undefined

### ISSUE THREAD

**Issue by fillumina** [hipster-labs/generator-jhipster-entity-audit#165]
generator-jhipster 7.0.1
I fixed the error at line 1560 of generator-base.js by adding the following code:

```    
function isBefore(e1, e2) {
      // fix by fillumina: Cannot read property 'changelogDate' of undefined
      if (!e1.definition && !e2.definition) {
        return 0;
      }
      if (!e1.definition) {
        return 1;
      }
      if (!e2.definition) {
        return -1;
      }
      // end fix
      return e1.definition.changelogDate - e2.definition.changelogDate;
 }
```

I really didn't have time to investigate further but that seemed to solve the issue for me.

**Comment by melloware** [comment]
I am running into this issue too

**Comment by marklcg** [comment]
Looks like the issue occurs when the .yo-rc.json file has entries in it for entities that no longer exist.  I assume JHipster maintains this file, but perhaps it happens if they are manually deleted incorrectly?

**Comment by mans-code** [comment]
Thanks @marklcg that was my issue. I just removeed the entity from .yo-rc.json and is working again :)

**Comment by walinabizada** [comment]
thanks it solved my issue as well.
