### ISSUE TITLE
I cant run the generator in Jhipster V7.x

### ISSUE THREAD

**Issue by smunir** [hipster-labs/generator-jhipster-entity-audit#166]
I am getting 'This generator (jhipster-entity-audit:app) requires yeoman-environment at least 3.0.0, current version is 2.10.3, try reinstalling latest version of 'yo' or use '--ignore-version-check' option'

yo global 3.1.1 is using yeoman-environment:2.10.3 and I am unable to use the generator. Please check

<img width="1359" alt="Screen Shot 2021-04-08 at 6 40 57 PM" src="https://user-images.githubusercontent.com/4279499/114038332-36b33880-989b-11eb-9b91-b37c22214655.png">

**Comment by smunir** [comment]
Looks like similar issue has been reported for other generators also. Please look at https://github.com/merlinofcha0s/generator-jhipster-flutter/issues/51 and https://github.com/yeoman/generator/issues/1279
As suggested in https://github.com/yeoman/generator/issues/1279#issuecomment-792669839 I am able to run the generator but now it's giving error `this.registerPrettierTransform is not a function`

**Comment by wael-sakhri** [comment]
@smunir  did you find a solution for this error ? 
`this.registerPrettierTransform is not a function`

**Comment by Lucifer3377** [comment]
please find the solution asap, not able to add audit extension to all entities with this command, using jhipster version 6.10.5...
The motive is to make every class extend the abstract audit interface which adds extra audit fields like created, modified, etc, and then get the liquibase changelog files updated respectively. Please reply asap.

**Comment by pojomojo1982** [comment]
Any idea when if and when this issue will be fixed? Any suggested known workarounds? New to jhipster so any guidance will be much appreciated. Can I downgrade jhipster manually in my existing app to get this to work?

**Comment by muyuanqiang7** [comment]
this module can not suport jhipster v7.x. 
when i install jhipster 6.10.5,then i install this module but still `this.registerPrettierTransform is not a function`
1. go to the npm gobal node_modules/generator-jhipster-entity-audit, if you install by -g
2. you can found module's node_modules default install jhisper@latest , then modify the package.json   "generator-jhipster": ">=6.0.0" to  "generator-jhipster": "6.10.5"
3. remove this module’s node_modules, then run npm i 
4. now you can use this module on jhipster v6.10.5

**Comment by edy-ap** [comment]
any update?

**Comment by smunir** [comment]
I checked out and used local version of 3.4.0, this worked for me? Have you tried this?

**Comment by edy-ap** [comment]
> I checked out and used local version of 3.4.0, this worked for me? Have you tried this?

can you exmplain me, how use v3.4.0, please?

**Comment by smunir** [comment]
> > I checked out and used local version of 3.4.0, this worked for me? Have you tried this?
> 
> can you exmplain me, how use v3.4.0, please?

Using local version of blueprint is a general thing. Luckily these instructions are mentioned in many blueprints. Checkout code of generator-jhipster-entity-audit and follow instructions from https://github.com/elhoutico/jhipster-primeng-blueprint#running-local-blueprint-version-for-development.

**Comment by edy-ap** [comment]
Thanks for you help, i will try

**Comment by naderwaled** [comment]
> Thanks for you help, i will try

hi,  do you fixed this issue?

**Comment by JeroenAdam** [comment]
I found out Jhipster now generates AuditingEntityListener and DatabaseConfiguration.java contains the annotation for enabling JPA auditing. I think this generator is not needed any longer.

**Comment by JeroenAdam** [comment]
This is going to be tackled here: https://github.com/jhipster/generator-jhipster/issues/18471

**Comment by DanielFran** [comment]
Closing, since we migrate to a new blueprint version.
If you found any issue with latest version, please open a new issue.

**Comment by akhilchakka-tudip** [comment]
Hi I am facing the same issue with jhipster version 7.5.5
