### ISSUE TITLE
"... is not a function" Error

### ISSUE THREAD

**Issue by vw98075** [hipster-labs/generator-jhipster-entity-audit#171]
I run 
```
yo jhipster-entity-audit 
```
against a JHipster 7.3.0 app. And I get  
```
error jhipster-entity-audit 

this.registerPrettierTransform is not a function
```

**Comment by Ebsan** [comment]
I'm getting the same error. Looks like they haven't updated the code for the new jhipster generator base?

**Comment by vw98075** [comment]
It is likely deprecated. I end up creating audit entities with actor, action type (create, update, and delete), and time stamp addition to the entity data.
