### ISSUE TITLE
bad request for create entity Test

### ISSUE THREAD

**Issue by alireza-hanifi** [hipster-labs/generator-jhipster-entity-audit#18]
when auditing is enabled "mvn test" will failed, because on createEntity() bad request returned.
the problem is the createDate and createBy will be empty.
when i set these fields on initEntity(), problem has solved.

**Comment by deepu105** [comment]
can you check with the latest release?

**Comment by alireza-hanifi** [comment]
yes

**Comment by deepu105** [comment]
@alireza-hanifi did you check is it working?

**Comment by deepu105** [comment]
this is fixed now
