### ISSUE TITLE
Incorrect package names and imports in templates

### ISSUE THREAD

**Issue by nitram84** [hipster-labs/generator-jhipster-entity-audit#185]
In latest git version some templates are still using the default package name 'com.mycompany.myapp'. I committed a fix here: https://github.com/nitram84/generator-jhipster-entity-audit/commit/bf4a0f8709b1978fef32dc73d324f25d2a54c650

**Comment by mshima** [comment]
👍

**Comment by DanielFran** [comment]
Closed with https://github.com/hipster-labs/generator-jhipster-entity-audit/pull/187
