### ISSUE TITLE
Add javers for sql databases

### ISSUE THREAD

**Issue by atomfrede** [hipster-labs/generator-jhipster-entity-audit#19]
The new [javers release](http://javers.org/documentation/features/#release-notes) supports sql databases too. So it would be cool to offer this as an option. 

@deepu105 Are you ok with an additional option?

**Comment by deepu105** [comment]
I used javers with sql long back how come its a new featuŕe?

**Comment by deepu105** [comment]
Btw im ok to add support :)

**Comment by atomfrede** [comment]
Its not a new feature, but the spring boot starter for sql is now officially available.

**Comment by deepu105** [comment]
Oh ok
