### ISSUE TITLE
No need to have @NotNull on AbstractAuditingDTO

### ISSUE THREAD

**Issue by marcelinobadin** [hipster-labs/generator-jhipster-entity-audit#21]
I have opened an issue on generator-hipster (https://github.com/jhipster/generator-jhipster/issues/3135) in order to ask to not have @NotNull annotation on AbstractAuditingEntity because it is unnecessary once you have @CreatedBy, @CreatedDate, ..., annotations that makes @NotNull irrelevant.

Once they remove that annotation, AbstractAuditingDTO can have only @ReadOnlyProperty as annotation on its fields. That way it will deliver the information and not request to be sent once you create a new resource.

**Comment by gandrade** [comment]
@deepu105 @jdubois I can do this change, but before let me know if I can proceed with this issue.

**Comment by deepu105** [comment]
Plz do, you are welcome

**Comment by gandrade** [comment]
Pull request available: #23
