### ISSUE TITLE
Plugin to manage images in Amazon S3

### ISSUE THREAD

**Issue by anirudh83** [hipster-labs/generator-jhipster-entity-audit#22]
Do we have a plugin to manage entity images in Amazon S3?

**Comment by deepu105** [comment]
Nope and its not on my roadmap as well

**Comment by anirudh83** [comment]
whats the best practise you would suggest i am making an app using Jhipster and have many images for an entity?

**Comment by anirudh83** [comment]
I can write a plugin using AWS Java SDK and submit a PR.

**Comment by deepu105** [comment]
I havent tried that so Im not sure, but I dont understand why you want to
save them in s3, the module already stores all the versions of entity as
json snapshots in the database. could you explain what you are trying to do
and the usecase?

Thanks & Regards,
Deepu

On Mon, Mar 14, 2016 at 4:24 PM, Anirudh Bhatnagar <notifications@github.com

**Comment by anirudh83** [comment]
I am making a travel app, so the destinations have multiple pics.
Say an entity destination would have 6 pictures. pictures in different sizes, thumbnails, 400x600 etc.
In one of my ROR app, I used the gem fog(https://github.com/fog/fog) to manage the pics in S3 and keep some id in DB for each entity.
Then while saving the image, the image would be stored in S3 with path constructed using that id and same while retreiving.
example :  path of image :  http://<aws-root><S3-bucket>/<unique-id>/thumbnail.jpg

**Comment by deepu105** [comment]
this is not a very generic requirement. This could be easily achieved by
versioning your images and referring that from the entity. I dont think
this is generic enough to be supported here. Im sorry. Having said that you
can add that as another module and use it in the mean ime or you can use a
customized fork as well



Thanks & Regards,
Deepu

On Mon, Mar 14, 2016 at 4:51 PM, Anirudh Bhatnagar <notifications@github.com

**Comment by anirudh83** [comment]
cool no issues.
found something similar , check this https://github.com/gregturn/spring-a-gram

**Comment by deepu105** [comment]
cool

Thanks & Regards,
Deepu

On Mon, Mar 14, 2016 at 5:44 PM, Anirudh Bhatnagar <notifications@github.com
