### ISSUE TITLE
If you already have AbstractAuditing on your class and you choose to not update the domain it inserts another 'extends AbstractAuditing'

### ISSUE THREAD

**Issue by marcelinobadin** [hipster-labs/generator-jhipster-entity-audit#24]
Sometimes I ran the jhipster:entity generator but choose to not update the domain class. Once it already has the 'extends AbstractAuditing' and I choose to use the audit on this entity, the generator inserts another 'extends AbstractAuditing' and break things up.

**Comment by marcelinobadin** [comment]
The same occurs on the DTO class.

**Comment by deepu105** [comment]
Yes it needs to be fixed i need to find a nice way to do it

**Comment by deepu105** [comment]
fixed via https://github.com/hipster-labs/generator-jhipster-entity-audit/releases/tag/v2.0.1
