### ISSUE TITLE
TypeError: jhipsterFunc.addJavaScriptToIndex is not a function

### ISSUE THREAD

**Issue by ashakhov** [hipster-labs/generator-jhipster-entity-audit#27]
Entity audit doesn't work with actual github version of JHipster. It throws `TypeError: jhipsterFunc.addJavaScriptToIndex is not a function` [here](https://github.com/hipster-labs/generator-jhipster-entity-audit/blob/master/generators/app/index.js#L188) and [here](https://github.com/hipster-labs/generator-jhipster-entity-audit/blob/master/generators/app/index.js#L301) because this function 
[was removed](https://github.com/jhipster/generator-jhipster/commit/26c3f2ceea9c760e81c30b4154cd80625aa15309) from JHipster. It has to be replaced with `jhipsterFunc.template`.

**Comment by deepu105** [comment]
Are you sure you are using Jhipster release version as master will not work

**Comment by deepu105** [comment]
I think you are using master, I havent update this repo for master yet

**Comment by ashakhov** [comment]
>Are you sure you are using Jhipster release version as master will not work
>Entity audit doesn't work with actual github version of JHipster
Yep.
