### ISSUE TITLE
Generator fails to start, module load issue

### ISSUE THREAD

**Issue by ashakhov** [hipster-labs/generator-jhipster-entity-audit#29]
Entity audit generator (v.2.0.1 from npm) fails to start:
```
module.js:341
    throw err;
    ^

Error: Cannot find module 'generator-jhipster'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/lib/node_modules/generator-jhipster-entity-audit/generators/app/index.js:6:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```
NodeJS 5.9.0 or 4.4.0 installed from nodesource deb repository, npm 3.8.2, freshly installed ubuntu 14.04.
Installed via 
`sudo npm install -g yo bower gulp generator-jhipster generator-jhipster-entity-audit`

**Comment by deepu105** [comment]
do you have JHipster 3.0 installed?

Thanks & Regards,
Deepu

**Comment by ashakhov** [comment]
Yes, it is installed in `/usr/lib/node_modules/generator-jhipster/package.json`
```
{
  "_args": [
    [
      "generator-jhipster",
      ""
    ]
  ],
  "_from": "generator-jhipster@latest",
  "_id": "generator-jhipster@3.0.0",
  "_inCache": true,
  "_installable": true,
  "_location": "/generator-jhipster",
...
```

**Comment by deepu105** [comment]
can you try the below and see, sometimes npm can be weird

1. delete the local `node_modules` in your project folder
2. do `npm i generator-jhipster -g`
3. do `npm i generator-jhipster-entity-audit -g`
4. run `npm i` in the project folder

see if this helps

**Comment by deepu105** [comment]
btw works fine for me

**Comment by ashakhov** [comment]
```
npm i generator-jhipster -g
npm i generator-jhipster-entity-audit -g 
```
It doesn't work without sudo due to `Error: EACCES: permission denied, access '/usr/lib/node_modules/generator-jhipster'`.

No, it didn't help. That's weird.

**Comment by deepu105** [comment]
thats weid as well.

this version needs JhIpster 3.0 to work so if its globally and locally available it should work.

how did yu launch the module?

**Comment by ashakhov** [comment]
Generated app using `yo jhipster` with existing .yo-rc.json in ~/test, then ran `yo jhipster-entity-audit`. Also tried generating project using master, still no luck.

```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "test",
    "packageName": "org.jhipster.test",
    "packageFolder": "org/jhipster/test",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "enableTranslation": true,
    "nativeLanguage": "ru",
    "languages": [
      "ru",
      "en"
    ]
  }
}

```

**Comment by deepu105** [comment]
Ok NPM is acting weird Im pushing a patch v 2.0.2 can you try with that just do `sudo npm i generator-jhipster-entity-audit -g` again

**Comment by ashakhov** [comment]
OK, now it is working. Thank you.

**Comment by sandeepatmakuri** [comment]
I am getting this error

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '../node_modules/generator-jhipster/generators/generator-constants.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
