### ISSUE TITLE
microservice architecture support

### ISSUE THREAD

**Issue by srnm** [hipster-labs/generator-jhipster-entity-audit#31]
Hi!

I tried adding entity audit support to an application and, while there were some error messages logged, the application still compiled/tested/ran ok.

However, adding entity audit support to the gateway that referenced the entity in the microservice application failed with the gateway code unable to be compiled.

Is support planned for the microservice architecture-style?
And thanks for the support for auditing when using the monolith-style!

**Comment by deepu105** [comment]
That's gonna take some time, in theory it should work but I might have
overlooked something. Will take a look when i have time

**Comment by marcelinobadin** [comment]
I am using it on microservice architecture. @srnm, you just need to add it to your service, and put the js/html files in the gateway and do the ajustments on the urls to make this js to work. 

It worked very fine for me.

**Comment by deepu105** [comment]
Would you mind doing a PR or documentation update on the readme.md file for
this?

Thanks & regards,
Deepu

**Comment by DanielFran** [comment]
Closing, since we migrate to a new blueprint version.
If you found any issue with latest version, please open a new issue.

**Comment by mshima** [comment]
Still relevant, but can be fixed with https://github.com/hipster-labs/generator-jhipster-entity-audit/issues/178
