### ISSUE TITLE
when I run jhipster:upgrade the overwrite question hangs the update

### ISSUE THREAD

**Issue by marcelinobadin** [hipster-labs/generator-jhipster-entity-audit#40]
I am trying to upgrade jhipster using jhipster:upgrade, but when it re-generates the entities it hangs over the question to overwrite me domain files once it runs the hook for this module.

The option I took was to remove the hook, run the upgrade then get it back.

Does anyone think that might have another better solution?

**Comment by deepu105** [comment]
Can you provide your apps yo-rc.json, node, npm and yo version

Thanks & regards,
Deepu

**Comment by amaillere** [comment]
I have the same problem here, jhispter:upgrade processes the module but I can't input an answer to the Ynaxd question...
npm 3.10.7
node 6.2.1
yo 1.7.0
yo-rc.json :
`{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.1",
    "baseName": "adn",
    "packageName": "fr.adn.annuaire",
    "packageFolder": "fr/adn/annuaire",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "rememberMeKey": "3f47be1023f31c6f019ec6922d3cb8c4a1a2c7e9",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr",
      "en"
    ],
    "jhiPrefix": "jhi"
  },
  "generator-jhipster-entity-audit": {
    "auditFramework": "custom"
  }
}`

**Comment by deepu105** [comment]
This seems like an issue in JHipster itself. Ill try to fix it there. Open an issue in JHipster project if you face this issue after the fix
