### ISSUE TITLE
Support pagination to retrive audits for an entity instead of using a hard limit

### ISSUE THREAD

**Issue by deepu105** [hipster-labs/generator-jhipster-entity-audit#44]
Support pagination to retrive audits for an entity instead of using a hard limit

**Comment by DanielFran** [comment]
Closing, since we migrate to a new blueprint version.
If you found any issue with latest version, please open a new issue.

**Comment by mshima** [comment]
Still relevant, but can be fixed with https://github.com/hipster-labs/generator-jhipster-entity-audit/issues/178
