### ISSUE TITLE
Timeouts when table gets too big

### ISSUE THREAD

**Issue by Panthro** [hipster-labs/generator-jhipster-entity-audit#45]
Hi

I was having a problem with this plugin, the following query was taking too long and causing a timeout:

```
select max(entityaudi0_.commit_version) as col_0_0_ from jhi_entity_audit_event entityaudi0_ where entityaudi0_.entity_type='xxxxxxxxxx' and entityaudi0_.entity_id=128200;
```

Doing an explain the result is:

| id | select_type | table | type | possible_keys | key | key_len | ref | rows  Extra |
| :-- | --- | --- | --- | --- | --- | --- | --- | --- |
| 1 | SIMPLE | entityaudi0_ | ALL | NULL | NULL | NULL | NULL | 504808 |

So what I did to fix was adding an index on the where fields (sorry, no command as I used a visual tool and too lazy).

That changed my explain to:

| id | select_type | table | type | possible_keys | key | key_len | ref | rows  Extra |
| :-- | --- | --- | --- | --- | --- | --- | --- | --- |
| 1 | SIMPLE | entityaudi0_ | ref | entity_id_type | entity_id_type | 265 | const,const | 1 |

And that speed up the query almost 99% (was taking 40s now taking less than 1 second).

I think it would be nice if you'd automatically add it to the liquibase table creation.

**Comment by Panthro** [comment]
It's worth noting that the table has over 500k rows and almost 1GB

**Comment by deepu105** [comment]
would you consider doing a PR for this?

**Comment by deepu105** [comment]
will be released after next jhipster version
