### ISSUE TITLE
Add support for JHipster 4.0 with angular2

### ISSUE THREAD

**Issue by deepu105** [hipster-labs/generator-jhipster-entity-audit#48]

**Comment by deshetti** [comment]
Hi @deepu105, is it going to fail with JHipster 4.2 or is not tested thoroughly?

**Comment by deepu105** [comment]
it will fail if you use ng2  as there is no support for that yet

**Comment by rohajda** [comment]
Do you know roughly when there can be version compatible with JH 4 and ng2? Just need to adjust some plans

**Comment by deepu105** [comment]
I dont have much time so cannot commit. But if you are willing to PR ill
merge and release

Thanks & regards,
Deepu

**Comment by rohajda** [comment]
i will try to check and learn how it works first. If not done by somebody else and once I know how to do it i will try but as of now i never done yo generator - its time to learn for me

**Comment by daparthimanu** [comment]
Hi @deepu105  I am trying to enable entity audit on my microservices using this module, I am running into this error. 
```
Error jhipster-entity-audit default
ERROR! I support only JHipster versions greater than ^3.6.0...If you want to use Entity Audit with an older JHipster version, download a previous version that supports the required JHipster version.
```
My Jhipster version: 4.0.5. Is there any workaround for this error?

Thanks

**Comment by kaidohallik** [comment]
@daparthimanu @deepu105 I made PR #56 to fix this error.  
But as workaround before new release you can try temporarily change in your `.yo-rc.json` from:
```
"jhipsterVersion": "4.0.5",
```
to
```
"jhipsterVersion": "3.12.2",
```
and change back after entity audit generation.
