### ISSUE TITLE
Liquibase error when generating entity audit module to an existing project

### ISSUE THREAD

**Issue by sw-enthusiast** [hipster-labs/generator-jhipster-entity-audit#59]
When running entity audit module on an existing project the generator creates new columns to the existing changelog of each entity, due to this liquibase throws database changelog validation error during the build. 

Suggestion: Instead of creating in the existing changeset create a new changelog file similar to when running `liquibase:diff `

**Comment by deepu105** [comment]
This will be released after next jhipster release
