### ISSUE TITLE
Could not compose module generator-jhipster-entity-audit

### ISSUE THREAD

**Issue by TBarina** [hipster-labs/generator-jhipster-entity-audit#63]
At the end of the process of creating a new entity using **JHipster entity <entityname>** I would expect to be asked  to enable audit since "jhipster-entity-audit module registers itself as a hook for Jhipster and the question to enable audit should be available during any new entity generation".
Instead I get the following error:

> Could not compose module generator-jhipster-entity-audit. 
> Make sure you have installed the module with 'npm -g generator-jhipster-entity-audit

Actually the generator IS installed. Executing yo jhipster-entity-audit manually completes the process.

Could anybody explain to me why the module is not properly composed?
Am I missing anything?

Thanks in advance

**Comment by deepu105** [comment]
Could you give details on how you were running the generator and tge
options used etc?

**Comment by TBarina** [comment]
My specs are as follows:

- OS: Centos 7.3
- Apache:  2.4.6 (httpd-2.4.6-45.el7.centos.4.x86_64)
- MySQL:  5.7.18
- Java: java version "1.8.0_121"
- Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
- Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
- Node: v7.10.0
- npm: 3.10.10
- Nower: 1.8.0
- Yeoman: 2.0.0
- generator-jhipster:  4.5.3
- generator-jhipster-entity-audit:  2.4.1

First I ran jhipster to create the application (Monolithic with classical session-based authentication mechanism and with MySQL DB for dev profile also).
Then I launched it with ./mvnw.
Everything was ok.

Then I ran "yo jhipster-entity-audit default" and ran ./mvnw again.

Finally I created a new entity: Node using:
jhipster entity Node
and got the compose error.

Running:
yo jhipster-entity-audit
and selecting Node entity was my workaround to continue my job but I expected that "jhispter entity Node" would launch this task without any error.

Do you need any more info?

Many thanks

**Comment by robertmilowski** [comment]
HI,

I have the same issue with this settings and simple jdl file
`{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.5.3",
    "baseName": "app",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "45136e32e0cf03352a214f802973852084d40e9d",
    "clientFramework": "angular1",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  },
  "generator-jhipster-entity-audit": {
    "auditFramework": "custom"
  }
}`

**Comment by deepu105** [comment]
This is fixed in generator-jhipster master branch. This will work only from next release of jhipster.
In the meantime you can use `yo jhipster:entity` command instead of `jhipster entity`
