### ISSUE TITLE
javers support not working anymore

### ISSUE THREAD

**Issue by gimoh** [hipster-labs/generator-jhipster-entity-audit#70]
Running the generator and selecting Javers auditing framework fails with:

```
ERROR! Copying template src/main/java/package/web/rest/_JaversEntityAuditResource.java failed. [ReferenceError: /home/gimoh/wrk/github.com/gimoh/generator-jhipster-entity-audit/generators/app/templates/src/main/java/package/web/rest/_JaversEntityAuditResource.java:58
    56|     public List<String> getAuditedEntities() {
    57| 
 >> 58|       return Arrays.asList(<%- auditedEntities %>);
    59|     }
    60| 
    61|     /**
```

After commit 72d0ae8a7db414308325b95005bd6252600640ea `auditedEntities` is now assigned inside `utils.js` in `#updateEntityAudit` but only conditionally and when I run it both conditions are false, i.e. `updateIndex === undefined` and ``this.fs.exists(`${javaDir}web/rest/JaversEntityAuditResource.java`) === false``.

I can submit a PR but will need some guidance on what the code is supposed to do. Could this block to update list of audited entities be moved out of `updateEntityAudit` and back into the main? In fact, would it make sense to put it into `#writeAuditPageFiles`?

**Comment by deepu105** [comment]
Javers part is in beta, so PR to improve is welcome. May @atomfrede can advice you as he did the javers part

**Comment by deepu105** [comment]
Oh and indeed if it helps to move the value of out of utils then thats fine too

**Comment by atomfrede** [comment]
I will have a look.

Am 10.08.2017 4:09 nachm. schrieb "Deepu K Sasidharan" <
notifications@github.com>:

**Comment by gimoh** [comment]
@atomfrede @deepu105 it's all right, got it, could you please review #71 ?

**Comment by deepu105** [comment]
That info is stored in the entity json file as a parameter something like `auditEnabled` I guess

**Comment by deepu105** [comment]
@gimoh v2.6.0 released for this https://github.com/hipster-labs/generator-jhipster-entity-audit/releases/tag/v2.6.0
