### ISSUE TITLE
Error to generate entity audit

### ISSUE THREAD

**Issue by jlopezjuy** [hipster-labs/generator-jhipster-entity-audit#74]
Hello i have this error when i trying to ejecute yo jhipster-entity-audit
i have jhipster 4.7.0, my app is microservice. jhipster-entity-audit 2.6.0

`module.js:471
    throw err;
    ^

Error: Cannot find module 'utils'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/jlopez/.npm-global/lib/node_modules/generator-jhipster-entity-audit/generators/app/index.js:10:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
`

my .yo-rc.json

`{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.seguritech.cadmobile",
      "nativeLanguage": "es"
    },
    "jhipsterVersion": "4.7.0",
    "baseName": "cadgateway",
    "packageName": "com.seguritech.cadmobile",
    "packageFolder": "com/seguritech/cadmobile",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "91c5f31d5705b964700cff9f97985aac13b71fd5",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "nativeLanguage": "es",
    "languages": [
      "es"
    ],
    "clientPackageManager": "yarn"
  },
  "generator-jhipster-entity-audit": {
    "auditFramework": "custom"
  }
}`

**Comment by hookszhang** [comment]
I got a same error, but jhipsterVersion:4.6.2

**Comment by hookszhang** [comment]
The `utils.js` is https://github.com/hipster-labs/generator-jhipster-entity-audit/blob/master/generators/utils.js

You can temporarily manual add utils.js to `/home/jlopez/.npm-global/lib/node_modules/generator-jhipster-entity-audit/generators/` folder.

It works for me.

**Comment by deepu105** [comment]
Fixed by https://github.com/hipster-labs/generator-jhipster-entity-audit/commit/e8c3965e21fdb056000422c7809936d4cda22760

Patch version released please update
