### ISSUE TITLE
generated index names for jhi_entity_audit_event too long for Oracle

### ISSUE THREAD

**Issue by BillCraven** [hipster-labs/generator-jhipster-entity-audit#77]
When you run the entity audit generator for a system that uses an Oracle database, the generated index names for the jhi_entity_audit_event table are too long (>30 characters) for Oracle to create. 

The workaround is to hand-edit the generated changeset file, but that's awkward.  

example audit entity generator session: 

$ !yo
yo
? 'Allo Craven,! What would you like to do? Jhipster Entity Audit

Make sure you are in the directory you want to scaffold into.
This generator can also be run with: yo jhipster-entity-audit

Welcome to the JHipster Entity Audit Generator! v3.1.0

? Choose which audit framework you would like to use. Custom JHipster auditing (works with SQL)
? Do you want to enable audit for all existing entities? Yes, update all
? Do you want to add an audit log page for entities? Yes

I'm Updating selected entities ....

Make sure these classes does not extend any other class to avoid any errors during compilation.
identical package.json
identical src/main/java/com/myco/audit/config/audit/AsyncEntityAuditEventWriter.java
identical src/main/java/com/myco/audit/config/audit/EntityAuditEventListener.java
identical src/main/java/com/myco/audit/config/audit/EntityAuditAction.java
identical src/main/java/com/myco/audit/config/audit/EntityAuditEventConfig.java
identical src/main/java/com/myco/audit/domain/EntityAuditEvent.java
identical src/main/java/com/myco/audit/repository/EntityAuditEventRepository.java
identical src/main/java/com/myco/audit/service/dto/AbstractAuditingDTO.java
   create src/main/resources/config/liquibase/changelog/20171220234244_added_entity_EntityAuditEvent.xml
 conflict src/main/resources/config/liquibase/master.xml
? Overwrite src/main/resources/config/liquibase/master.xml? overwrite
    force src/main/resources/config/liquibase/master.xml
identical src/main/java/com/myco/audit/domain/AbstractAuditingEntity.java
 ... my entities 
    force src/main/webapp/app/admin/entity-audit/entity-audit-event.model.ts
    force src/main/webapp/app/admin/entity-audit/entity-audit-modal.component.html
    force src/main/webapp/app/admin/entity-audit/entity-audit-modal.component.ts
    force src/main/webapp/app/admin/entity-audit/entity-audit-routing.module.ts
    force src/main/webapp/app/admin/entity-audit/entity-audit.component.html
    force src/main/webapp/app/admin/entity-audit/entity-audit.component.ts
    force src/main/webapp/app/admin/entity-audit/entity-audit.module.ts
    force src/main/webapp/app/admin/entity-audit/entity-audit.service.ts
    force src/main/java/com/myco/audit/web/rest/EntityAuditResource.java
    force src/main/webapp/app/admin/admin.module.ts
    force src/main/webapp/app/layouts/navbar/navbar.component.html

I'm all done. Running yarn install for you to install the required dependencies. If this fails, try running the command yourself.

....

If we then compare the generated version of the change set to a working one:

too long (generated): 
`<createIndex indexName="idx_entity_audit_event_entity_id"
            tableName="jhi_entity_audit_event">
            <column name="entity_id" type="bigint"/>
        </createIndex>
        <createIndex indexName="idx_entity_audit_event_entity_type"
            tableName="jhi_entity_audit_event">
            <column name="entity_type" type="varchar(255)"/>
        </createIndex>`

shortened:
`<createIndex indexName="idx_entity_audit_event_entity_id"
            tableName="jhi_entity_audit_event">
            <column name="entity_id" type="bigint"/>
        </createIndex>
        <createIndex indexName="idx_entity_audit_event_entity_type"
            tableName="jhi_entity_audit_event">
            <column name="entity_type" type="varchar(255)"/>
        </createIndex>`

**Comment by DanielFran** [comment]
Closing seems fixed with latest version
