### ISSUE TITLE
Translation Not found in labels with project without i18n

### ISSUE THREAD

**Issue by poolebu** [hipster-labs/generator-jhipster-entity-audit#78]
![captura de pantalla 2017-12-29 a la s 1 12 59 p m](https://user-images.githubusercontent.com/4500001/34436882-08c7662c-ec9a-11e7-8927-584ec607a1c4.png)

**Comment by deepu105** [comment]
Please provide details like your apps `.yo-rc.json` , module version used etc

**Comment by poolebu** [comment]
Here is the `.yo-rc.json`. 
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.catwizard.jenis"
    },
    "jhipsterVersion": "4.13.1",
    "baseName": "jenis",
    "packageName": "com.catwizard.jenis",
    "packageFolder": "com/catwizard/jenis",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "238507a46bef78437fc2d7ad70ed847c7886b8dd",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false,
    "cacheProvider": "no",
    "enableHibernateCache": false
  },
  "generator-jhipster-entity-audit": {
    "auditFramework": "javers"
  }
}
```
Module Version
```
yo jhipster-entity-audit --version
2.0.0
```

**Comment by deepu105** [comment]
Please change your jwt key as you posted it publicly here.

Did you generate the application originally without translation? Coz the screenshot shows that translation related code is present

**Comment by poolebu** [comment]
That screenshot belongs to the audit log screen. The variable for generating it is set on false `"enableTranslation": false,` because I did not choose internalization when creating the jhipster project. I tested it on a new test project, same issue. I tested on a project with translation and it worked

```
"enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "es"
    ]

```
![captura de pantalla 2018-01-07 a la s 6 28 00 p m](https://user-images.githubusercontent.com/4500001/34652032-2da5984c-f3d9-11e7-8d23-d99d91813807.png)

**`"enableTranslation": false,**

![captura de pantalla 2018-01-07 a la s 6 27 52 p m](https://user-images.githubusercontent.com/4500001/34652024-1b1faf78-f3d9-11e7-9db8-f9f54538f8ff.png)

I will use the translation module anyways.... and probably most users do, just wanted to report the bug.

**Comment by deepu105** [comment]
I guess no i18n may not be handles in the templates, do you wanna do a PR to fix

**Comment by poolebu** [comment]
Yes, but I will need some directions no what files to do the changes.

**Comment by deepu105** [comment]
The client siide files under the angular folder would need to add
translation directives conditionally


Thanks & Regards,
Deepu

**Comment by DanielFran** [comment]
Closing seems fixed with latest version
