### ISSUE TITLE
Unable to Build Hibernate SessionFactory

### ISSUE THREAD

**Issue by gigantedocil** [hipster-labs/generator-jhipster-entity-audit#85]
Hi, I'm trying to use this generator to add the auditing functionalities to my entities on a monolithic JHipster application. The generation works well, but when I run ./mvnw the following happens:

`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory`

And I can't run the app. I've tried using the yo jhipster-entity-audit default first and then using the yo jhipster-entity-audit and selecting only 2 entities, but the error still happens.

**Comment by deepu105** [comment]
what version of JHipster are you using? please post your .yo-rc.json files

**Comment by DanielFran** [comment]
Closing seems fixed with latest version
