### ISSUE TITLE
Transaction mangement  and rollback

### ISSUE THREAD

**Issue by Abderrahmen36** [hipster-labs/generator-jhipster-entity-audit#87]
Hello 

I'm new to use the Entity audit module , it work very well for my requirement.
i just want to know if a transaction fail for persisting the entity audit for some reason , the main transaction to persist or update or delete the entity will fail too ? 

When i throw an exception for example in AsyncEntityAuditWriter Class , the exception wil not propagate so the entity is modified but no entityAudit is persisted for example

**Comment by DanielFran** [comment]
Closing seems fixed with latest version
