### ISSUE TITLE
jhiTranslate present even when internationalization is disabled

### ISSUE THREAD

**Issue by mulhauser** [hipster-labs/generator-jhipster-entity-audit#89]
Hi,

I have just used generator for entity audit for my jhipster project. 
I have found an issue: jhiTranslate attribute still present in .html files even though internationalization is disaled on my project. I have seen "if ... then ... else" in .ts files and it works great.

**Comment by deepu105** [comment]
Would you like to do a PR to fix it

**Comment by mulhauser** [comment]
I’d like to PR but i don’t know how to make the same "if...then...else" on .html file

**Comment by mulhauser** [comment]
Is this like .ts file with <%_ ... _%> ?

**Comment by deepu105** [comment]
Yes you can do the same

use <% ... %> if it is inline and <%_ ... _%> if the content is in a newline

Thanks & Regards,
Deepu

**Comment by murdos** [comment]
Fixed with https://github.com/hipster-labs/generator-jhipster-entity-audit/pull/90
