### ISSUE TITLE
Getting error with Spring JPA Example query

### ISSUE THREAD

**Issue by mkysoft** [hipster-labs/generator-jhipster-entity-audit#93]
I try to use Example for querying entities.

Audit lastModifiedDate and createdDate field automatically added to query in where section.

**Comment by mkysoft** [comment]
I found the reason;
lastModifiedDate and createdDate set as Instance.now() on class generation. So Hibernate added them to query in where. You can remove assign and set hem in getter for hot fix.

**Comment by DanielFran** [comment]
Closing seems fixed with latest version
