### ISSUE TITLE
getAngular2AppName not found

### ISSUE THREAD

**Issue by mkysoft** [hipster-labs/generator-jhipster-entity-audit#96]
getAngular2AppName function renamed as getAngularXAppName in generator base with v5.
So it is giving below error:

> events.js:183
>       throw er; // Unhandled 'error' event
>       ^
> 
> TypeError: this.getAngular2AppName is not a function
>     at module.exports.setupGlobalVar (myproject/node_modules/generator-jhipster-entity-audit/generators/app/index.js:172:37)
>     at Object.<anonymous> (myproject/node_modules/yeoman-generator/lib/index.js:399:25)
>     at myproject/node_modules/run-async/index.js:25:25
>     at new Promise (<anonymous>)
>     at myproject/node_modules/run-async/index.js:24:19
>     at self.env.runLoop.add.completed (myproject/node_modules/yeoman-generator/lib/index.js:400:11)
>     at runCallback (timers.js:810:20)
>     at tryOnImmediate (timers.js:768:5)
>     at processImmediate [as _immediateCallback] (timers.js:745:5)

**Comment by deepu105** [comment]
This is fixed but not released yet. I'll make a release probably this weekend
