### ISSUE TITLE
Travis tests are broken

### ISSUE THREAD

**Issue by deepu105** [hipster-labs/generator-jhipster-entity-audit#98]
The Travis tests are broken for a while. Need to check why.

@pascalgrimaud @ruddell if any of you guys have some spare time please help me with this

**Comment by deepu105** [comment]
Updated node to see if it fixes the issues. But I guess build was broken even before the node version issue

**Comment by pascalgrimaud** [comment]
@deepu105 : I can improve the Travis build here. Just assign it to me, and I will do that

**Comment by deepu105** [comment]
@pascalgrimaud thanks a lot

**Comment by pascalgrimaud** [comment]
I'm starting to have a look on this.
But in Travis, we have this message:
```
ERROR!  I support only JHipster versions greater than >=4.10...
            If you want to use Entity Audit with an older JHipster version, download a previous version that supports the required JHipster version.
```

Before going further, is this module compatible with JHipster 5 ?

**Comment by deepu105** [comment]
I need to find time to make it compatible

**Comment by murdos** [comment]
Fixed with https://github.com/hipster-labs/generator-jhipster-entity-audit/pull/125
