### ISSUE TITLE
Generated JaversEntityAuditResource uses wrong type for entity Id

### ISSUE THREAD

**Issue by nicoraynaud** [hipster-labs/generator-jhipster-entity-audit#99]
Hi,

First of all, thanks for your work here, greatly appreciated.

While we were trying to integrate this plugin with our JHipster applications, we faced one specific issue.

Here is the code generated in JaversEntityAuditResource.java class :
```
public ResponseEntity<EntityAuditEvent> getPrevVersion(@RequestParam(value = "qualifiedName") String qualifiedName,
                                                           @RequestParam(value = "entityId") String entityId,
                                                           @RequestParam(value = "commitVersion") Long commitVersion)
```

In this signature, the entityId param as a String. This is a problem when we use Long as IDs for our entities because when Javers tries to fetch its globalId matching our id, it automatically adds quotes to the SQL query it generates.
I'm not sure how but the final query ends up like this : 
`SELECT global_id_pk FROM jv_global_id where local_id = "'1001'" AND type_name = "nc.opt.sumo...."`
Where we should have
`SELECT global_id_pk FROM jv_global_id where local_id = "1001" AND type_name = "nc.opt.sumo...."`

A small fix to this issue is to set the RequestParam type to Long (matching our entities IDs) and it fixes the issue.

Let me know if you share this issue or if your need more info on this.

Once we are on the same page, I could do a PR to fix this.

**Comment by atomfrede** [comment]
Hi @nicoraynaud 

your solution seems right. Looks like javers changed something under the hood as it worked once I implemented it that way. So go ahead with a PR :+1:

**Comment by nicoraynaud** [comment]
@atomfrede : I am not sure why this didnt pass the build : i really changed a minor thing here :)

any hint on when this might be merged ?

**Comment by DanielFran** [comment]
Closing seems fixed with latest version
